using System;

namespace OtobüsBiletRezarvasyon.Formlar
{
    public partial class FrmWord : DevExpress.XtraEditors.XtraForm
    {
        public FrmWord()
        {
            InitializeComponent();
        }

        private void FrmWord_Load(object sender, EventArgs e)
        {
            string fileName = "Test.docx";
            using (DevExpress.XtraRichEdit.RichEditDocumentServer srv =
                new DevExpress.XtraRichEdit.RichEditDocumentServer())
            {
                DevExpress.XtraRichEdit.API.Native.Document doc = srv.Document;
                doc.AppendText("This document is generated by Word Processing Document API");
                DevExpress.XtraRichEdit.API.Native.CharacterProperties cp = doc.BeginUpdateCharacters(doc.Paragraphs[0].Range);
                cp.ForeColor = System.Drawing.Color.FromArgb(0x83, 0x92, 0x96);
                cp.Italic = true;
                doc.EndUpdateCharacters(cp);
                DevExpress.XtraRichEdit.API.Native.ParagraphProperties pp = doc.BeginUpdateParagraphs(doc.Paragraphs[0].Range);
                pp.Alignment = DevExpress.XtraRichEdit.API.Native.ParagraphAlignment.Right;
                doc.EndUpdateParagraphs(pp);
                srv.SaveDocument(fileName, DevExpress.XtraRichEdit.DocumentFormat.OpenXml);
            }
            System.Diagnostics.Process.Start(fileName);
        }
    }
}